language: c

sudo: false

services:
  - docker

cache:
  apt: true

script:
  - make

after_success:
  - docker login "$DOCKER_REPOSITORY" --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push "$DOCKER_REPOSITORY"

notifications:
  email: true
